### ISSUE TITLE
IE-specific -ms-clear styling breaks CSP

### ISSUE THREAD

**Issue by joux3** [JedWatson/react-input-autosize#105]
The inline style element used by the `-ms-clear` [workaround](https://github.com/JedWatson/react-input-autosize/blob/master/src/AutosizeInput.js#L131) breaks [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). Would it be possible to have an extra prop that would control whether such a workaround is applied (I don't believe the current approach can be made CSP-safe)?

(Extra note: both the element and the style element refers to `state.id` which should probably be `state.inputId` which is defined in [the constructor](https://github.com/JedWatson/react-input-autosize/blob/master/src/AutosizeInput.js#L19)).

**Comment by JedWatson** [comment]
Thanks for calling that out, I've made it optional and updated the docs on how to work around this yourself if you need to.
