### ISSUE TITLE
Bug with changing font-family/font-size

### ISSUE THREAD

**Issue by AndreyMiloserdov** [JedWatson/react-input-autosize#114]
If you are created styles for input, and change it on fly, your sizer not update styles,
so, where are no correct autoresize on change font size or family or others...

this.sizer node has only the initial props and not updates on input props updated.

hack to temporary solve this problem in code:
`    this.view.input.copyInputStyles();
    this.view.input.updateInputWidth();`

**Comment by JedWatson** [comment]
You're right, I've added this gotcha with workarounds to the readme.

**Comment by cancan101** [comment]
I think this is a different issue than this ticket but when / if the ["Rendered Font"](https://developers.google.com/web/updates/2013/09/DevTools-answers-What-font-is-that) used for the container changes, the size will also change but not trigger a re-calculation of the needed width.

**Comment by intelligence** [comment]
@cancan101 Also seeing this issue. Once the web font is rendered the placeholder will be slightly cut off as it's slightly wider than initial paint font.

Any idea for a quick fix?

**Comment by cancan101** [comment]
I subscribed to the font loaded event and then called a repaint on the auto size component.

**Comment by intelligence** [comment]
That's great! How does one call a repaint? New to React – would be thankful for an example :)

**Comment by duongthienlee** [comment]
It's great that there's a workaround to this bug, but I have no idea how to call copyInputStyles() ?
this is my component. I'm using react hook. Have no idea to call copyInputStyles and updateInputWidth when headerTextState.size changes

    <AutosizeInput
                        name={headerTextState.id}
                        inputClassName="headerInputClass"
                        value={headerTextState.content}
                        style={{ fontSize: headerTextState.size }}
                        inputStyle={{ fontSize: headerTextState.size, cursor: `${disableDragging ? 'text' : 'move'}` }}
                        inputRef={(node) => setHeaderInputRefState(node)}
                        onChange={(event) => inputOnchange(event)}
                    />

**Comment by duongthienlee** [comment]
How do I call copyInputStyles()? I'm using react hooks now, can't use ref on AutosizeInput to call that function at all.
I know I can set a key to trigger rerender, but how to call copyInputStyles () if I don't want to use key.
