### ISSUE TITLE
Not all number fields need extra space

### ISSUE THREAD

**Issue by Kilian** [JedWatson/react-input-autosize#120]
The extra space for the up/down arrows in number fields is hardcoded: https://github.com/JedWatson/react-input-autosize/blob/master/src/AutosizeInput.js#L112 whilst not all type="number" fields show these arrows. It would help me if this "extra width" was a prop instead that would default to 16 for number fields, but that I could overwrite to 0 when I need to.

**Comment by JedWatson** [comment]
I published a fix for this in `2.2.0`, you can now use the `extraWidth` prop to override the number field padding.
