### ISSUE TITLE
Infinite loop in Safari

### ISSUE THREAD

**Issue by uiureo** [JedWatson/react-input-autosize#14]
Yosemite 10.10.5 
Safari 8.0.8 (10600.8.9)

I had an issue that causes Safari hang. 
I'm sorry it's hard to reproduce in general case. But I would like to share my workaround for someone in the future.

The issue was that `scrollWidth` of the sizer changes by 1px after `state.inputWidth` is updated.

`scrollWidth` of the sizer is affected by `state.inputWidth`, so this causes infinite state updates like this.

this.state.inputWidth | newInputWidth
------------ | -------------
1 | 40
40 | 41
41 | 40
40 | 41
41 | 40
...  | ...

``` javascript
if (newInputWidth !== this.state.inputWidth) {
 this.setState({
   inputWidth: newInputWidth
 });
}
```

It might be a bug in Safari. 

## Workaround
My workaround is ignoring 1px error. I know this is not a good solution, but works well for now.

``` javascript
if (Math.abs(newInputWidth - this.state.inputWidth) > 1) {
 this.setState({
    inputWidth: newInputWidth
 });
}
```
https://github.com/uiureo/react-input-autosize/commit/4370bd5002f9fa2cdf302447a84a66e3ead6618e

I think this case is rare, so feel free to close this issue.

**Comment by uiureo** [comment]
In my environment, it seems this issue has been solved.
I have no idea about the reason.

**Comment by EvanSimpson** [comment]
I'm experiencing this as well in both Chrome and Safari, so definitely not a Safari bug.
My workaround is to extend AutosizeInput and add a `shouldComponentUpdate` function that checks that props aren't shallow equal or that the the change in `inputWidth` is greater than 1. If there isn't a better solution to the 1px bug, then it might be worth making the `shouldComponentUpdate` function be configurable through props or some other means.

**Comment by jandom** [comment]
I was able to re-create this issue on Firefox 80.0b3 and I'm now trying to reproduce it. The behavior is just as described above https://github.com/JedWatson/react-input-autosize/issues/14#issue-104869421
