### ISSUE TITLE
Refs and cleanup

### ISSUE THREAD

**Issue by jossmac** [JedWatson/react-input-autosize#141]
Might be time to bring the source into-line with modern conventions:

- flow
- prettier
- React -- 16.X
  - `createRef()`
  - `forwardRef()`

Ref #129

**Comment by burtek** [comment]
Doesn't need to be flow though, can be typescript as well

**Comment by artisologic** [comment]
Definitely agree for the new refs stuff, right now it's not well supported at all, so can't really use them as is.
