### ISSUE TITLE
Add maxLength

### ISSUE THREAD

**Issue by jmtavares** [JedWatson/react-input-autosize#149]
Would it be possible to have a maxLength prop?

**Comment by joelc-konradgroup** [comment]
@jmtavares Were you able to get around this somehow? I'm also going to need a maxLength prop for my uses. Was there a workaround that you found?

**Comment by jmtavares** [comment]
Yes @joelc-konradgroup , you can use just like this
`<AutosizeInput                          
    name="name"
    type="text"
    value={name}
    maxLength={100}/>`
