### ISSUE TITLE
add ref for sizer div for width queries

### ISSUE THREAD

**Issue by DoubleFinned** [JedWatson/react-input-autosize#156]
I was doing some custom alignment with AutoSizeInput components and ran into problems when getting the clientWidth from the input ref. My problems were fixed by getting the client width of the sizer div instead, then using that for my alignment logic.

I got the dom element of the sizer manually like this:
`sizerDomElement = inputRef.parentElement.children.item(1)`

This seems like a bad way to do this, is it feasible to be able to make a change to be able to get the ref via a sizerRef prop in the same way we can obtain the inputRef - through the inputRef prop.

**Comment by designbyadrian** [comment]
Why is this ticket closed? What was the solution?
