### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by daggmano** [JedWatson/react-input-autosize#163]
Component should be updated for latest React changes.

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

      * Move data fetching code or side effects to componentDidUpdate.
      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

      Please update the following components: AutosizeInput

**Comment by ranneyd** [comment]
https://github.com/JedWatson/react-input-autosize/pull/166

**Comment by Methuselah96** [comment]
I've made [a fork](https://github.com/react-select-oss/react-input-autosize) with the fix for this released as [`react-input-autosize-oss@2.2.3`](https://github.com/react-select-oss/react-input-autosize/blob/master/HISTORY.md#v223--2020-11-12).
