### ISSUE TITLE
Error: Cannot find module 'babel-preset-env'

### ISSUE THREAD

**Issue by lozcalver** [JedWatson/react-input-autosize#182]
Hi,

I’m using React 17 and trying to use `react-select: 4.3.1`. My app is compiling fine, but as soon as I try to `import Select from 'react-select';` I get the following error:

```
ERROR in ./node_modules/react-input-autosize/lib/AutosizeInput.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-env'
```

I’m not really sure what’s going on here. I have the following dependencies in _my_ package.json:

```
"@babel/core": "^7.15.5",
"@babel/preset-env": "^7.15.6",
"@babel/preset-react": "^7.14.5"
```

Any ideas? Thanks!

**Comment by Methuselah96** [comment]
Looks like you're using Webpack. My guess is that you're not excluding `node_modules` when running Babel.

**Comment by Methuselah96** [comment]
Take a look at the `exclude` in [this usage example](https://github.com/babel/babel-loader#usage) of `babel-loader` and make sure you're excluding `node_modules` in your Webpack config.

**Comment by lozcalver** [comment]
I am, and I _think_ I’ve correctly excluded `node_modules` but I’ll double check now

**Comment by lozcalver** [comment]
Nope, I hadn’t 😅 thanks for the speedy help @Methuselah96!
