### ISSUE TITLE
Div or no div

### ISSUE THREAD

**Issue by OKNoah** [JedWatson/react-input-autosize#19]
In your textarea component, I believe there is no surrounding div, but in this component there is. Just a bit of an inconsistency which slightly complicates things in my app where I use both.

**Comment by JedWatson** [comment]
@OKNoah I think you may be giving me credit for something I haven't done... are you talking about `react-textarea-autosize` by @andreypopp?

That component is internally very different from this one, it would take a fairly significant refactor to update `react-input-autosize` to not have a wrapping `<div>` around it.
