### ISSUE TITLE
this.refs.input is not of type element

### ISSUE THREAD

**Issue by john-osullivan** [JedWatson/react-input-autosize#22]
Hi, I'm trying to use your excellent-looking [react-select](https://github.com/JedWatson/react-select) library and am running into a bug.  When I instantiate a Select field on the page for the first time, AutosizeInput is failing with the following error from line 46 of the AutosizeInput.js file:

`Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

I tried debugging by replacing the `this.refs.input` with a `this.refs.input.getDOMNode()` so it would get past that error, but similar issues sprang up with `this.refs.sizer` on the following lines.  Even when I replaced them both, the same error'd reference to `this.refs.input` was breaking throughout the file.  I wasn't sure if replacing all of them was the best approach. 

The project is using React 0.14.0, I'm not sure what could be going wrong.  The field itself, by the way, is rendering completely wonky: 
![image](https://cloud.githubusercontent.com/assets/3820981/10656220/9d80e318-784a-11e5-8a58-d15815fd65ec.png)

Thoughts?

EDIT: I tried replacing every single `this.refs.[...]` in the file with `this.refs.[...].getDOMNode()` and was able to get rid of errors, but the input still didn't render correctly.  It did show all provided options in a dropdown and let me select them, but everything was unstyled and I got these error messages:

`Warning: React can't find the root component node for data-reactid value .0.1.0.3.2.0.0.0:$packageForm-2.0.1.1.2. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.`

`ReactMount.js?ed21:710 Uncaught TypeError: Cannot read property 'firstChild' of undefined`

**Comment by john-osullivan** [comment]
Ah, I found my problem -- I'm trying to use React v0.14 but am actually using React v0.13.3_7 because React is being provided to me by Meteor.  This looks like an issue which Meteor needs to solve by upgrading their React library, nothing on your end.  Thanks for making a great-looking library!  I look forward to using it soon.

**Comment by JedWatson** [comment]
> Thanks for making a great-looking library! I look forward to using it soon.

This really made me smile :grinning: hope they get you onto React 0.14 soon!

**Comment by puhastudio** [comment]
Running `meteor update` seems to update react to version 0.14.1_1. But there is no styling applied to / included with the component. There is some discussion on the topic here as well: https://forums.meteor.com/t/react-npm-components-with-css/12540
