### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollWidth' of undefined

### ISSUE THREAD

**Issue by mzstic** [JedWatson/react-input-autosize#31]
Hi,
I'm using your react-select component but it keeps throwing errors. But I think the real problem is here.

First error shown is
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

And then following
Uncaught TypeError: Cannot read property 'scrollWidth' of undefined
which appears in updateInputWidth() function in AutosizeInput component in the first condition

``` js
typeof this.refs.sizer.scrollWidth === 'undefined'
```

Here is listing of `npm ls | grep react` to show you versions I'm working with

├─┬ react@0.14.3
├── react-dom@0.14.3
├─┬ react-dropzone-component@0.8.1
├─┬ react-select@1.0.0-beta6
│ └── react-input-autosize@0.6.5

**Comment by jgwconsulting** [comment]
Yes, I'm getting this too, using ReactSelect which depends on this component. Seems to only throw an error in Internet Explorer for me.

**Comment by mzstic** [comment]
It occurrs to me in chrome. After updating to newest version of everything.
I even tried react-select@0.9... but with the same result

**Comment by sp-ivan-ortega** [comment]
Hi, i have the same problem, any solution @mzstic or @jgwconsulting Thanks!

**Comment by npasquet** [comment]
Still no solution on that issue ?

**Comment by L3V147H4N** [comment]
I started getting this error only after including jquery and bootstrap to my project, could be related?

**Comment by bartoszhernas** [comment]
I am working in multiple different technologies and JS with npm is giving us the majority of headaches.

Has anyone solved this?

**Comment by laifharwood** [comment]
I just ran into this problem and changed line 68 to:

if (!this.isMounted() || typeof this.refs.sizer === 'undefined'){

And it worked for me.

**Comment by moog16** [comment]
For some odd reason I found a node_modules directory inside the react-select directory. I deleted the node_modules, and it worked.

**Comment by hariram1975** [comment]
Try this out,  new webpack.ProvidePlugin({ $: "jquery", jQuery: "jquery" }),

**Comment by JedWatson** [comment]
The mount functionality has been rewritten and I can't reproduce this so I believe it's been fixed
