### ISSUE TITLE
Cursor lagging input in Safari

### ISSUE THREAD

**Issue by Bertg** [JedWatson/react-input-autosize#36]
I originally found this issue in the [react-select](https://github.com/JedWatson/react-select) component and reported it on [this ticket](https://github.com/JedWatson/react-select/issues/733). 

Now I've recorded the same behaviour on the demo page of this project as well. 

![react-input-autosize_cursor_lag](https://cloud.githubusercontent.com/assets/1434/12546843/ea50bd9c-c34c-11e5-976f-688093c6e588.gif)

When typing at a reasonable speed the cursor seems to be lagging the input of the component. However the input is still OK. However when typing fast the input might actually get compromised.

We have a bunch of other components using the same "controlled value" mechanism where this is not happening.

This was recorded with the latest Safari on OSX. We do not see this on latest Chrome.

**Comment by alexanderchan** [comment]
I dug a bit more into this and it appears to have been introduced in #24.  My guess is there is something strange between the timing of the nextFrame and reading the styles. 

At least doing this resolves the safari problem:
```
componentDidUpdate() {
    this.updateInputWidth();
  // this.queueUpdateInputWidth();
  },
```

**Comment by Bertg** [comment]
Can this commit be created in a PR?

**Comment by JedWatson** [comment]
I've fixed this by removing the delay around resizing, I don't know why it started braking but suspect it may be something internal in a new version of React. From my testing (not exhaustive, I don't have a version of IE handy) it seems the `queueUpdateInputWidth` method isn't needed at all anymore.
