### ISSUE TITLE
Strange resizing behavior in a modal in Safari (seems to be calculating widths slightly too small)

### ISSUE THREAD

**Issue by moodysalem** [JedWatson/react-input-autosize#51]
We are using the react-select 1.0 beta version

In our modal ( from fastmodel-layout-components http://fastmodelsports.github.io/fastmodel-layout-components/ ) we are seeing strange behavior with the select where the input doesn't resize to the correct width and wraps

![screen shot 2016-06-08 at 12 36 22 pm](https://cloud.githubusercontent.com/assets/7897876/15904261/e55adc80-2d75-11e6-80be-be951f56df2d.png)
![screen shot 2016-06-08 at 12 36 16 pm](https://cloud.githubusercontent.com/assets/7897876/15904262/e55c8756-2d75-11e6-8bb6-07042268b94f.png)
![screen shot 2016-06-08 at 12 36 11 pm](https://cloud.githubusercontent.com/assets/7897876/15904263/e55e98b6-2d75-11e6-8a8a-103a1754532e.png)
![screen shot 2016-06-08 at 12 36 06 pm](https://cloud.githubusercontent.com/assets/7897876/15904260/e5593fce-2d75-11e6-8330-8f7ff82f54a1.png)

The same selector outside the modal appears to work
![screen shot 2016-06-08 at 12 40 01 pm](https://cloud.githubusercontent.com/assets/7897876/15904322/2d9d839e-2d76-11e6-9d2b-3412344ec0e0.png)

As far as I can tell all the font settings are the same

Any idea what might be going on here?

**Comment by JedWatson** [comment]
Can't reproduce this
