### ISSUE TITLE
input style.width not correctly set for minWidth='5px'

### ISSUE THREAD

**Issue by caedmon** [JedWatson/react-input-autosize#59]
The PropType for minWidth states that either string or number is valid.
react-select passes '5px' for minWidth.
But props.minWidth is used to set state.inputWidth in a way that is only valid if minWidth is a number, both in getInitialState() and updateInputWidth().
Then render() unconditionally appends 'px' to state.inputWidth to set inputStyle.width.
So in the case of minWidth='5px' you get inputStyle.width='5pxpx' which React apparently converts to '2px'.  Set minWidth='5' and you get the expected '5px' width.

While it would be easy enough to fix this for the 'px' case, I think the comparison in updateInputWidth() would make it more difficult to handle other units on minWidth, e.g. '%' or 'em'.

Simply taking away the string option for minWidth would fix react-input-autosize and would cause a warning in react-select and others that are passing string values.

**Comment by kurttheviking** [comment]
Just got bit by this as well; was getting mysterious "Invalid argument" errors from IE clients and we traced it down to this particular error.

**Comment by kurttheviking** [comment]
@JedWatson Would you be open to a PR that implements @caedmon's proposed fix:

```
Simply taking away the string option for minWidth would fix react-input-autosize and would cause a warning in react-select and others that are passing string values.
```

Or, at the very least, a PR that removes the [unchecked addition of 'px' to the `minWidth` prop](https://github.com/JedWatson/react-input-autosize/blob/master/src/AutosizeInput.js#L110). This would fix the bug that produces `5pxpx` when used with react-select.

**Comment by JedWatson** [comment]
This has been fixed in react-select

**Comment by pehhuishi** [comment]
Hi, I would like to change the width of the select-react how can i do it??
