### ISSUE TITLE
React 15.2 breaking changes

### ISSUE THREAD

**Issue by reactima** [JedWatson/react-input-autosize#60]
Related issue 
https://github.com/JedWatson/react-select/issues/1073

react-select is broken cause react-input-autosize is not capatible with React 15.2 
`Warning: Unknown prop `minWidth` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by AutosizeInput)
    in div (created by AutosizeInput)
    in AutosizeInput (created by Select)
    in div (created by Select)
    in div (created by Select)`

**Comment by JedWatson** [comment]
I just fixed this and published a new version `1.1.0`, will get the change pushed through to `react-select` asap too
