### ISSUE TITLE
Support for input[type="number"]

### ISSUE THREAD

**Issue by amannn** [JedWatson/react-input-autosize#62]
Browsers like Chrome display controls for number inputs:

<img width="51" alt="screen shot 2016-07-27 at 11 25 21" src="https://cloud.githubusercontent.com/assets/4038316/17172396/d6bc8f0a-53ec-11e6-993d-e7f0ca2928f2.png">

This results into some parts of the number being hidden. Is there a good way to solve this? The screenshot shows an input field where I entered `123`.

**Comment by chreez** [comment]
Were you able to override the "type" attribute on the AutoSizeInput? It doesn't work for me.

**Comment by xuopled** [comment]
It could be awesome if `input[type="number"]` could be supported. @JedWatson Are you interested by a PR about that?

**Comment by JedWatson** [comment]
I've added basic support for this, if anyone has a better idea let me know
