### ISSUE TITLE
Auto focus by default

### ISSUE THREAD

**Issue by shardool-freightwalla** [JedWatson/react-input-autosize#69]
I had a query regarding autofocus in this component.

I have used the autofocus component  in my project. I was wondering how can i have the AutoSizeInput to have a default onFocus state. Currently if i click on it it gets the focus

**Comment by ethorz** [comment]
You can set focus by ref. Create ref for input and call method this.input.focus() in componentDidMount.

**Comment by JedWatson** [comment]
@ethorz is correct, you can also set the `autoFocus` prop and the input will focus when it is mounted. I've added an example to the demo.

**Comment by designbyadrian** [comment]
@JedWatson Please add valid parameters to the README file 🙏

`autoFocus` works! I'd just like to add that since React 16.3, you'd create refs with React.createRef(), then access the input via `this.myInputRef.current.input.focus()`
