### ISSUE TITLE
Debounced input misses typed characters in IE11

### ISSUE THREAD

**Issue by caseyross** [JedWatson/react-input-autosize#72]
When using an asynchronous handler with the onChange event in IE11, it's possible for characters to be skipped so that the input value does not reflect what was typed.

This is technically a bug in React itself:
https://github.com/facebook/react/issues/7027

Though React will fix the bug in version 16.0, this remains a huge problem for our IE users until then. We hope you'll consider using the onInput event internally instead of onChange, which should resolve the issue (we've tried it out locally and it works great). We'd be happy to submit a PR for this if desired.

**Comment by codehtmai** [comment]
Has anyone found a workaround for this yet? This is causing a lot of issues for us currently, as we need to support IE11.

**Comment by JedWatson** [comment]
Sorry I didn't get to this earlier, but looks like it was resolved in react 15.6.1 so should be good now
