### ISSUE TITLE
placeholderIsMinWidth seemingly does nothing and function responsible for updating width doesn't fire soon enough

### ISSUE THREAD

**Issue by joeyfigaro** [JedWatson/react-input-autosize#75]
**Placeholder with a forced min-width via scss**
![](https://d3vv6lp55qjaqc.cloudfront.net/items/1a090l3w2n3T1O0g3K3g/Image%202017-02-15%20at%207.25.39%20PM.png?X-CloudApp-Visitor-Id=37226ef4a83c849204ef6a1efa01836b&v=497ff1eb)

**First spot where function should be firing**
![](https://d3vv6lp55qjaqc.cloudfront.net/items/3v2G131h2V1x3r2R1B0Z/Image%202017-02-15%20at%207.26.02%20PM.png?X-CloudApp-Visitor-Id=37226ef4a83c849204ef6a1efa01836b&v=977bde95)

**When function actually begins to fire ($60,000,000,000,000,000,000,000,000,0)**
![](https://d3vv6lp55qjaqc.cloudfront.net/items/3e08282V0V2Z083m3q0X/Image%202017-02-15%20at%207.27.28%20PM.png?X-CloudApp-Visitor-Id=37226ef4a83c849204ef6a1efa01836b&v=1d40f12c)

Using rems, if that matters.

**Comment by JedWatson** [comment]
Although I can see the problem in your screenshots, I can't reproduce it, sorry!
