### ISSUE TITLE
Switch to vanilla JS classes

### ISSUE THREAD

**Issue by leo** [JedWatson/react-input-autosize#80]
<img width="798" alt="screen shot 2017-04-14 at 23 26 06" src="https://cloud.githubusercontent.com/assets/6170607/25056586/27cddfa2-216a-11e7-9c24-b9bae0e2b278.png">

**Comment by cheton** [comment]
Also need to replace React.PropTypes references with prop-types.

See React 15.5.0 deprecation warnings at https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by agirton** [comment]
This can be closed as #79 will fix this.

**Comment by jochenberger** [comment]
fixed via #79
