### ISSUE TITLE
Support for React 15.5

### ISSUE THREAD

**Issue by loispostula** [JedWatson/react-input-autosize#81]
React 15.5 is the last release before the 16. Which will have breaking change, is there any thought about updating the lib to React 15.5?

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by enapupe** [comment]
IDK why you closed it but..
I see there's some code changes regarding react 15.5 already on master.
Any chances we get a release soon?

I was reading they should release 16 at some point in the second half of this year..
