### ISSUE TITLE
Missing dependencies for `create-react-class` and `prop-types`

### ISSUE THREAD

**Issue by unimonkiez** [JedWatson/react-input-autosize#84]
Hey,
My build is failing because of a recent update of this library.

Log - 
``` bash
Error: Cannot find module 'create-react-class'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function._resolveFilename (/home/uv/dev/t2k-js-common/node_modules/mocha-webpack/lib/util/registerRequireHook.js:42:34)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/uv/dev/t2k-js-common/node_modules/react-input-autosize/lib/AutosizeInput.js:7:19)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
...
```

Seems like you added usage to a library but forgot to add it to dependency\peer dependency.
Thanks in advance.

**Comment by mAiNiNfEcTiOn** [comment]
Duplicated of #82

**Comment by dandonahoe** [comment]
@unimonkiez Related temporary fix is doing the following:

Install that module manually
`npm install create-react-class`

Then somewhere in your code, add:
`require('create-react-class');`

This was driving me insane yesterday after installing `react-select` and having everything explode. As a freak accident, I came across this and figured it out:

https://facebook.github.io/react/docs/react-without-es6.html

**Comment by AdamBrodzinski** [comment]
Why is this not a breaking change? I'm using `react-select` with a pinned version (rc.2) and a recent deploy brings the entire app down.

**Comment by mooncakelmn** [comment]
+ 1 for this, breaking my apps as well

**Comment by the-spyke** [comment]
So, somebody added a new dependency without bumping the major version number and broke semver?

**Comment by corzzo** [comment]
Temporary fix:

npm install --save react-input-autosize@**1.1.0**

**Comment by lochstar** [comment]
Yep, this got me as well. Rolling back to 1.1.0.

**Comment by starsinmypockets** [comment]
Sigh you broke the internet

**Comment by kyle-ssg** [comment]
😅

**Comment by kyle-ssg** [comment]
http://www.squce.com/wp-content/uploads/2014/07/jLZz4Na.gif

**Comment by rahulthampi** [comment]
This error can be temporarily fixed by installing create-react-class
`npm i --save create-react-class`

**Comment by lochstar** [comment]
Amazing this hasn't been fixed yet. @JedWatson are you on holidays?

**Comment by LDubya** [comment]
some people just want to watch the world burn.

**Comment by nitruxa** [comment]
@JedWatson bump! ping!

**Comment by jkahrs595** [comment]
While I'm good and mad and motivated, how can I prevent this from happening again with another project? I've already removed the carets in my package.json, but how can I make sure that my dependencies aren't pulling in weird things I don't want them to?

**Comment by MichaelDeBoey** [comment]
This is fixed with `v1.1.4` (#83)

**Comment by azotova** [comment]
I use the build from CDN:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-with-addons.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/classnames/2.2.5/index.js"></script>
<script src="https://npmcdn.com/react-input-autosize/dist/react-input-autosize.js"></script>
<script src="https://npmcdn.com/react-select/dist/react-select.js"></script>
```
and get the following error: Cannot find module 'react'.

This comes from the line 742 here https://npmcdn.com/react-input-autosize@1.1.4/dist/react-input-autosize.js (i.e. from create-react-class module), combined with line 754 (`{"./factory":1,"react":undefined}`). It looks like the create-react-class module was not browserified properly.

The temporary fix is to explicitly specify the version (`https://npmcdn.com/react-input-autosize@1.1.0/dist/react-input-autosize.js`), but it would be great to get a permanent solution.

**Comment by jochenberger** [comment]
#85 fixes this

**Comment by Sibabale** [comment]
I installed the `create-react-class` module but I get this error:

`Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/home/sibabale/projects/siba/react-playlist/node_modules/webpack-dev-server/client/index.js'
    at Object.19 (bundle.js:794)
    at __webpack_require__ (bundle.js:679)
    at fn (bundle.js:89)
    at Object.18 (bundle.js:783)
    at __webpack_require__ (bundle.js:679)
    at 0 (bundle.js:725)
    at bundle.js:728`

**Comment by RickyReskyAnanda** [comment]
TypeError: Cannot read property 'string' of undefined
./node_modules/react-select-plus/node_modules/react-input-autosize/lib/AutosizeInput.js
D:/react/build/node_modules/react-select-plus/node_modules/react-input-autosize/lib/AutosizeInput.js:31
  28 | var AutosizeInput = React.createClass({
  29 |   displayName: 'AutosizeInput',
  30 |   propTypes: {
> 31 |     className: React.PropTypes.string,
  32 |     // className for the outer element
  33 |     defaultValue: React.PropTypes.any,
  34 |     // default field value
View compiled

**Comment by echarso** [comment]
same problem here
