### ISSUE TITLE
Can I load this package from CDN?

### ISSUE THREAD

**Issue by nonelove** [JedWatson/react-input-autosize#98]
I tried to find a CDN link for this package, but I couldn't. Please let me know if you know the way to load this package from CDN. Thanks.

**Comment by pateketrueke** [comment]
Yes, you can.

https://bundle.run/react-input-autosize@1.1.4

As stated on #95 seems like the standalone version is broken, but RollupJS is black-magic!

**Comment by JedWatson** [comment]
standalone version is working now with 2.0.0

another cdn option is [unpkg](https://unpkg.com/) and you can load the umd bundle like this:

https://unpkg.com/react-input-autosize@2.0.0/dist/react-input-autosize.min.js

see [the standalone example](https://github.com/JedWatson/react-input-autosize/blob/master/examples/dist/standalone.html) for how to use it
