### ISSUE TITLE
Styles from input not being copied to hidden div

### ISSUE THREAD

**Issue by mvf4z7** [JedWatson/react-input-autosize#99]
I noticed that font related styles from the visible input were not being properly copied to the hidden div used for calculating the size. This was causing the size of the input to be incorrect (too large), as the font-size of the div was larger than that of the input.

After changing this [line](https://github.com/JedWatson/react-input-autosize/blob/master/src/AutosizeInput.js#L68) to return when the compoennt is NOT mounted it seemed to fix the issue

e.g. `if (!this.mounted || !window.getComputedStyle) {`

**Comment by slavab89** [comment]
Someone already opened the exact same PR https://github.com/JedWatson/react-input-autosize/pull/91 😄  We're still waiting for it to get merged

**Comment by JedWatson** [comment]
Should be fixed as of `1.2.0`
